### ISSUE TITLE
define etch

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1199]
At the moment layer_stack only supports `grow`  type layers

How can we define etch layers in plugins such as tidy3d?

DONE:
- [x] Define etch in Klayout 2.5D  https://github.com/gdsfactory/gdsfactory/pull/1318
- [x] Define Layer_stack for simulators (Lumerical, tidy3d ....) https://github.com/gdsfactory/gdsfactory/pull/1318

**Comment by simbilod** [comment]
Shortest term, we should just change the "etch" layers so that they are "grow" layers, but of oxide into the material they are etching. 

So for instance, a slab etch over a core layer could be defined as a block of oxide from zmin = slab_maximum to zmax = core_maximum

Eventually we should have the layers define a process instead of a geometry, with the ability to "build" the geometry from the process or simulate it. I have been playing with this on a branch https://github.com/simbilod/gdsfactory/blob/process_definition/gdsfactory/processes.py
