### ISSUE TITLE
klayout webapp viewer running on your jupyter notebooks

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1223]
Thanks to [Kweb](https://github.com/gdsfactory/kweb) you can now have klayout webapp viewer running on your jupyter notebooks

![image](https://user-images.githubusercontent.com/4514346/216777259-299fe92e-11b5-4dc7-9862-187532a571bb.png)

# How can we get the kweb server running in the docs?

![image](https://user-images.githubusercontent.com/4514346/216777032-fae94be3-2e4c-4a7e-8096-e026e3eae3a0.png)

@proppy
@klayoutmatthias
@sebastian-goeldi
@tvt173

**Comment by proppy** [comment]
I wonder if https://ipython.readthedocs.io/en/stable/config/integrating.html could help.

As Jupyter rendering could hint at a different representation type depending if it's meant for interactive usage or static rendering within the docs, and allow gdsfactory to choose between including an iframe or rendering a static image.

**Comment by sebastian-goeldi** [comment]
This part is relatively easy. Declare jupyter_server as a global. I had it wrong in my mind about the declaration. Globals are module wide after reading about it, so it should be reasonably safe. Otherwise you have the problem that the setting of the server variable is not properly propagated between scopes.


What is left to do is, there are error dumps of websocket disconnects when you refresh cells. I haven't fully understood how to catch them without having the cell crash

**Comment by joamatab** [comment]
Thank you Proppy and Sebastian

I was also surprised it does not work on binder either

![image](https://user-images.githubusercontent.com/4514346/216781143-589c8ab6-81d2-40be-b052-d13949686c16.png)
