### ISSUE TITLE
SiEPIC Verification errors

### ISSUE THREAD

**Issue by SebyLeDanger** [gdsfactory/gdsfactory#1244]
Dear Sir/Madam,

I am trying to layout MZIs using GDSfactory in VSCode.

Along the way, I met 1 obstacle that I have been unable to solve for now:

1. When I do the SiEPIC Verification in KLayout, I have an error saying that my grating couplers are not correctly oriented. I have the same problem by running an example of the ubcpdk library

You can find my project here : https://github.com/SebyLeDanger/gdsfactory-mzi

PS: I also have one question :

Is there a way to specify in python the EBeam technology so that I don't have to change it by hand in KLayout after running my code ?

**Comment by joamatab** [comment]
Hi Seby,

i looked at your layout and it looks good to me

![image](https://user-images.githubusercontent.com/4514346/217289309-92b38793-e972-4973-9a77-7c152fe01da2.png)

I think the issue is on the SiEPIC verification script

@lukas-ubc

**Comment by SebyLeDanger** [comment]
Hi Joaquin,

Thank you for taking the time to look at my layout.

I know that the gratings are correctly oriented but there must be something off between gdsfactory and the Siepic verification. 

If you look at the properties of one grating, you will see that the rotation angle is not 0° but 270°. So I guess the reference position in gds is not the same than in the Siepic tool.

**Comment by lukasc-ubc** [comment]
Hi folks,

The issue is that the grating coupler cell polygons were rotated when you created the PDK.  Please see the original cell in the PDK: https://github.com/SiEPIC/SiEPIC_EBeam_PDK/blob/master/klayout/EBeam/gds/EBeam/ebeam_gc_te1550.gds
Notice that it is facing to the right, whereas the cell in your PDK is facing left.

It is a really bad idea to modify foundry-provided cells. In this case we actually do an IP replacement for the grating couplers, so if you have rotated the contents of cell, after we replace it, the polygons will be pointing the opposite direction!

The definitions for verification Design for Test rules are specified in DFT.XML, as described here: https://github.com/SiEPIC/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions (search for DFT).

and for the EBeam PDK here:
https://github.com/SiEPIC/SiEPIC_EBeam_PDK/blob/master/klayout/EBeam/DFT.xml

Finally, note that we are now using Black Box versions for all the grating couplers, since different foundries have different fabrication process bias, and require calibration of the coupler for each process.  Then we perform an IP replacement just prior to fabrication.

Thank you
Lukas

**Comment by SebyLeDanger** [comment]
Dear Lukas,

I am not exactly sure what you mean by :

> The issue is that the grating coupler cell polygons were rotated when you created the PDK

I have checked the ebeam_gc_te1550.gds file in the ubcpdk folder and it is pointing right with a 0° degree angle. So I am a bit confused. What could cause such a rotation when I create the pdk ?

Moreover, in the ubcpdk I could not find the Black Box versions of the GC components that I have to use. 

Thank you for taking the time to help me,
Sébastien

**Comment by lukasc-ubc** [comment]
@joamatab showed me yesterday that this file was pointing left. 

The missing cells need to be imported into the GDSfactory implementation of the PDK.

**Comment by SebyLeDanger** [comment]
Maybe it is because, when I open the ebeam_gc_te1550 from python it is pointing left but when I open the gds file from the windows explorer it is pointing right. Is there something rotating/mirroring the gc when importing the gds file in python ?

# Windows explorer
![image](https://user-images.githubusercontent.com/77792157/217583409-9f93941c-7e15-4b1b-bdcc-79dae0f197c9.png)

# Python
![image](https://user-images.githubusercontent.com/77792157/217583900-e4a72ccd-967e-44eb-bdd7-ce7178ec7f34.png)

**Comment by joamatab** [comment]
Hi Sebastian and Lukas,

I sent a PR that fixes the issue

as Lukas suggested we create a new container cell that has the original grating coupler rotated

![image](https://user-images.githubusercontent.com/4514346/217588811-7b1aa9e4-02d2-47e9-b894-6c9559bdbcbd.png)

**Comment by joamatab** [comment]
If you `pip install ubcpdk --upgrade` your design works now


![image](https://user-images.githubusercontent.com/4514346/217604455-8a2d68cd-240d-4056-a729-1512803dc0af.png)

Here is a PR with the new grating coupler design

https://github.com/SebyLeDanger/gdsfactory-mzi/pull/1

**Comment by SebyLeDanger** [comment]
Thanks a lot to both of you !

**Comment by lukasc-ubc** [comment]
Hi Sebastien,

The original source PDK is here: https://github.com/SiEPIC/SiEPIC_EBeam_PDK

The PDK cells were imported by Joaquin and team at GDSfactory, into what they call “ubcpdk”.  

Making sure that ubcpdk is consistent with SiEPIC_EBeam_PDK is not automated. Presently they are independent and might not be identical.

I hope that clarifies.

thank you
Lukas

**Comment by joamatab** [comment]
yes, Thomas made a script for that

https://github.com/gdsfactory/ubc/blob/main/update_source.sh
