### ISSUE TITLE
1nm snapping issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1666]
1nm snapping issues

snapping can happen

see `gdsfactory.components.mzi` snapping inwards, 

snapping 1nm outwards are even more obvious as they leave 1nm gap

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/a2a303d3-a668-4c05-a4df-c5d9c2b38637)

```python
    c = mzi(cross_section="strip")
    c = gf.routing.add_fiber_array(c)
    c.show()
```

**Comment by joamatab** [comment]
this can be fixed with `write_gds(transform_invalid_references=True)` but also creates issues in some other layouts

**Comment by tvt173** [comment]
@joamatab, as discussed before, please make sure you are not doing any explicit snapping anywhere (i.e. snapping ports or lengths) when you have that flag set to `True`, as it might conversely cause snapping issues in that case. You can quickly test this out by temporarily commenting out the body of those functions so that they do nothing, and rebuilding your layout... I'd be interested to see if there are still any snapping errors after taking these precautions...
