### ISSUE TITLE
bring 3.7 testing back?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1744]
Some people are still using python3.9 and we have some new dependencies (kfactory) that require python >=3.10

We need to bring the python3.7 tests back

Possible Solutions:

- rewrite difftest and use klayout only
- migrate kfactory to python3.7 
- add a minimal version of the tests

@SkandanC

**Comment by SkandanC** [comment]
Difftest isn't the inly thing using kfactoyr though, the fill and spacing fixers are all using kfactory, and are kfavtory utilities.

Kfacory to py3.7, perhaps, the issue is match case is used in some places, which is inly py3.10 syntax

Would things break for pre 3.10 if we kept tests to 3.10? I don't think there'd be any issues for any plugins, or for gdstk.


________________________________
From: Joaquin Matres ***@***.***>
Sent: Wednesday, June 7, 2023 10:05 PM
To: gdsfactory/gdsfactory ***@***.***>
Cc: Skandan Chandrasekar ***@***.***>; Mention ***@***.***>
Subject: [gdsfactory/gdsfactory] bring 3.7 testing back? (Issue #1744)


Some people are still using python3.9 and we have some new dependencies (kfactory) that require python >=3.10

We need to bring the python3.7 tests back

Possible Solutions:

  *   rewrite difftest and use klayout only
  *   migrate kfactory to python3.7

@SkandanC<https://github.com/SkandanC>

**Comment by joamatab** [comment]
What do you think of  the simplest solution of running some bare bones tests?

https://github.com/gdsfactory/gdsfactory/pull/1745

**Comment by SkandanC** [comment]
Sure, sounds good.
________________________________
