### ISSUE TITLE
near2far meep grating coupler example

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#195]
How could we add a near2far grating coupler example to `notebooks/gdsfactory/plugins/meep/002_gratings.ipynb`  ?

@simbilod

**Comment by simbilod** [comment]
We'd need to define a new simulation where instead of fiber and fiber ports, there is a near2far monitor. We`d then need define a new analysis function that parses the near2far instead of the S-params.

It`s not so bad, this is how I had it setup originally, so I have some code lying around. It was mostly based on the [Simpetus example](http://www.simpetus.com/projects.html#meep_outcoupler).

**Comment by joamatab** [comment]
We moved plugins development to it to https://github.com/gdsfactory/gplugins
