### ISSUE TITLE
grid snapping fixes

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2118]
The recent grid snapping fixes are causing gaps in non-manhattan connections

You can take a look at `gdsfactory/samples/snap_bends.py`

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/1824d929-580a-40d5-9a72-04baa44018fb)

@tvt173 
@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Yeah, I was wondering whether this wouldn't show up. This is the problem if you force ports on grid. That's why I only see the problem being solved in case of kfactory with virtual components and in your case probably selectively add the port snapping when a manhattan component amd not when used for non-manhattan routing/components

**Comment by tvt173** [comment]
yes, snapping ports to grid will inherently break non-manhattan connections like this. the "flatten invalid refs" fix used at the time of writing the GDS only works because the points are unsnapped and maintain their original floating-point precision
