### ISSUE TITLE
fix spiral_inner_io

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2257]
How can we fix the polarity of the bends?

```python
    import gdsfactory as gf

    xs1 = gf.cross_section.pn()
    xs2 = xs1.mirror()

    c = gf.components.spiral_inner_io_fiber_array(
        cross_section=xs1,
        cross_section_bend=xs2,
        waveguide_spacing=20,
        asymmetric_cross_section=True,
        length=30e3,
    )
    c.show()

```

I think we already fixed this one, not sure how it came back

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/fce1e4b1-6273-4c15-bf78-ba4676f8fce5)

@simbilod

**Comment by simbilod** [comment]
General mirroring was first added in #1050 

This bug was fixed in #1433

The old mirror, used in the fix, used to change the cross-section in place, which has since been deprecated. It looks like the new immutable cross-section does not actually return a mirrored cross-section:

```
import gdsfactory as gf

xs1 = gf.cross_section.pn()
xs2 = xs1.mirror()

xs_before = []
xs_after = []

for section in xs1.sections:
    xs_before.append(section.offset)
for section in xs2.sections:
    xs_after.append(section.offset)

print("before mirror: ", xs_before)
print("after mirror: ", xs_after)
```

Output:

```
before mirror:  [-0.0, -0.0, -4.0, 4.0, -4.25, 4.25, -4.5, 4.5]
after mirror:  [-0.0, -0.0, -4.0, 4.0, -4.25, 4.25, -4.5, 4.5]
```

In component:

```
c = gf.Component()

c << gf.components.straight(cross_section=xs1)
sec = c << gf.components.straight(cross_section=xs2)
sec.movey(-30)

c.show()
```

![image](https://github.com/gdsfactory/gdsfactory/assets/46427609/ad662b13-32a7-400b-a42a-02ead20d740a)
