### ISSUE TITLE
Serialization for Transition & Section doesn't always work for variable widths

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#2465]
**Describe the bug**
When creating a variable width `Transition` or `Section`, if the user uses a function to return the custom width function, Pydantic will just serialize the `width_function`, `offset_function` (in the case of `Section`), and `width_type` (for `Transition`) as a string with the name of the width function. 

In the example below, this results in the `@gf.cell` decorator seeing the same `width_func` when serializing the `Section`, `s`, though the actual function has been created using different `num_periods` arguments. As a result, all of the resulting extruded paths, `p`, are identical.

```
import numpy as np
import gdsfactory as gf


def get_custom_width_func(n: int = 5):
    def _width_func(t):
        return 3 + np.cos(2 * np.pi * t * n)
    return _width_func


c = gf.Component()

P = gf.path.straight(length=40, npoints=100)

for i, num_periods in enumerate([1, 5, 10]):
    width_func = get_custom_width_func(n=num_periods)
    s = gf.Section(width=0, width_function=width_func, offset=0, layer=(1, 0))
    X = gf.CrossSection(sections=(s,))

    c2 = gf.Component()

    p = c2 << gf.path.extrude(P, cross_section=X)
    label = c2 << gf.c.text(f"{num_periods=}", size=5)

    label.movex(label.xmin, p.xmax + 2)
    label.movey(label.y, p.y)

    c.add_ref(c2).movey(-i * 15)

c.show()
```
Which ends up creating 3 identical components:
![image](https://github.com/gdsfactory/gdsfactory/assets/53101766/943f2058-577d-4195-bb9f-92ff7a807429)

## Suggested Fix
I propose we fix this by serializing the _output_ of the function, like so:
```
class Section(BaseModel):
    ...
    @field_serializer("width_function", "offset_function")
    def serialize_functions(self, func: Callable | None) -> str | None:
        if func is None:
            return None
        t_values = np.linspace(0, 1, 11)
        return ",".join([str(round(width, 3)) for width in func(t_values)])
```
and
```
class Transition(BaseModel):
    ...
    @field_serializer("width_type")
    def serialize_width(self, width_type: WidthTypes | Callable) -> str | None:
        if isinstance(width_type, str):
            return width_type
        t_values = np.linspace(0, 1, 10)
        return ",".join([str(round(width, 3)) for width in width_type(t_values)])
```

making these modifications, the behavior is as expected:
![image](https://github.com/gdsfactory/gdsfactory/assets/53101766/3e6954c4-59f0-4400-85e6-e49b5ae6d2a1)

**Comment by EStegenburgs** [comment]
There is a bug with this fix. Overall, all somehow works but widths are returned 3 times from one function call using `width_function`. I have tried many ways to drop/ignore the extra two arrays but unsuccessfully. The below part of the code produces this issue - there should be only one array output but there are three.

```
def func(x):
    print('len(x)='+str(len(x)) + '; x='+str(x))
    y = np.sin(50*x)
    mpl.plot(x, y)
    return y

XS = gf.Section(width=0, offset=0, layer=(10,0), width_function=func)
gf.path.extrude(mypath, gf.CrossSection(sections=[XS]));
```
Example of the output:
![image](https://github.com/gdsfactory/gdsfactory/assets/35864327/bd262762-8e85-48fc-9d5b-ff6d118e8dc2)

By deleting the below code part from **`cross_section.py`** this issue is solved.
```
    @field_serializer("width_function", "offset_function")
    def serialize_functions(self, func: Callable | None) -> str | None:
        if func is None:
            return None
        t_values = np.linspace(0, 1, 11)
        return ",".join([str(round(width, 3)) for width in func(t_values)])
```
I.e., from the above example I get:
![image](https://github.com/gdsfactory/gdsfactory/assets/35864327/b7f523f9-a812-4596-95c2-68e88c1137f6)

Can someone advise how to properly implement the fix such that there aren't these extra generated lists or what should be done?
