### ISSUE TITLE
fix routing

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2787]
some routing cases are still broken

compared to gdsfactory v7 (left). See issues in main (right)

![Image](https://github.com/gdsfactory/gdsfactory/assets/4514346/72bf6ea9-36a8-4221-b254-624462420fb5)

@sebastian-goeldi 
@tvt173

**Comment by sebastian-goeldi** [comment]
Is the right one 4 (or at least 2) separte calls to `route_bundle` or a single one?

If it's a single one, it will not work as the end ports must be a single bank of ports and not overlap with the starting bounding box.

That would explain why it doesn't work.

I also noticed that routing fails if the routes are exactly lining up perfectly behind each other. E.g. both end ports are angle=0 and end port has same `y` as start port. I suspect the router fails to pick a side and doesn't do anything, which causes it to then fail horribly when it picks the next step, because the previous routes aren't where they are supposed to be.

**Comment by sebastian-goeldi** [comment]
Fixed by https://github.com/gdsfactory/kfactory/pull/337
