### ISSUE TITLE
make gdsfactory klayout package to depend on klive and meta_info_ports

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2850]

**Comment by sebastian-goeldi** [comment]
does this even still work? what is the gdsfactory klayout package doing?

**Comment by tvt173** [comment]
the point of this is as we discussed earlier: so that users can get all the gdsfactory-related tools with one package install in klayout

i don't particularly care how it's done, but if there's already a "gdsfactory" package, i think it would make sense that it is the go-to one that has everything. it will be the easiest to find.

i think Joaquin said that it currently installs just the generic tech and maybe a few other things

**Comment by joamatab** [comment]
yes, at the moment the gdsfactory package only installs the layermap

i can take care of this issue

**Comment by sebastian-goeldi** [comment]
Oh. If it's just that and not the full bundle, just add `klive` and `metainfo_ports` as dependencies to the package
