### ISSUE TITLE
update to latest simphony

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#388]
See https://github.com/gdsfactory/gdsfactory/tree/simphony_latest2

@SkandanC 

Still some test failing

**Comment by SkandanC** [comment]
Hello @joamatab,

I took a look at the branch and ran pytest. I see which tests are failing now.

I also tried to install the .dat files from the `gdslib` repo through `install.bat` as you had suggested, but some files are still not available (such as the one in the attached screenshot).

![image](https://user-images.githubusercontent.com/100642027/168489163-785a9786-6294-474a-8428-9f5f7339c5c6.png)


My previous PR fixes most of the failing tests, except the ones with missing .dat files. There was also a test for the `coupler` component which was failing; the reason for this was that Simphony's components take units in m, unlike SiPANN which takes units in nm.

Please let me know if I have missed any failing tests that I haven't addressed.

**Comment by joamatab** [comment]
Hi Skandan,

even in your PR the tests were not passing
https://github.com/gdsfactory/gdsfactory/runs/6428031102?check_suite_focus=true
so i had to revert your changes back after merging them,

make sure you checkout the branch `data` on gdslib repo

This is what i see when i run pytests on the `simphony_latest` branch

![image](https://user-images.githubusercontent.com/4514346/168861857-b223ec75-48d6-459b-bd22-c689427993c3.png)

**Comment by joamatab** [comment]
i made some progress but still not working

https://github.com/gdsfactory/gdsfactory/commit/5a794d35b926be5a888920ec9621c2d46649b98d

What are the advantages of the new simphony 0.6.1 versus the 0.3.0?

@austp
@sequoiap
@SkandanC

**Comment by SkandanC** [comment]
Hello @joamatab,

The reason my last PR was failing was because the simphony version gdsfactory was installing is very old. Changing that to the newest version would fix that. 

![image](https://user-images.githubusercontent.com/100642027/169067127-1c2c2806-ae63-42e5-a6ec-d485c84b800a.png)

I managed to find the .dat files and I am delighted to say that fixed more of the failing tests. Now I have 3-4 more tests failing on the `works-with-simphony-latest` branch, and am working on it now. 

Regarding the differences between the older and newer versions of Simphony, Austen and Seqouia are more qualified to answer that since they know more about the older versions.

**Comment by SkandanC** [comment]
Hello @joamatab,

The reason my last PR was failing was because the simphony version gdsfactory was installing is very old. Changing that to the newest version would fix that. 

![image](https://user-images.githubusercontent.com/100642027/169067127-1c2c2806-ae63-42e5-a6ec-d485c84b800a.png)

I managed to find the .dat files and I am delighted to say that fixed more of the failing tests. Now I have 3-4 more tests failing on the `works-with-simphony-latest` branch, and am working on it now.

**Comment by joamatab** [comment]
Hi Skandan,

Sounds good, I met professor Camacho yesterday and he mentioned that there is a time domain solver coming soon in simphony, so it makes sense to upgrade to the latest simphony. Let me know when the tests are passing and I'm happy to merge your changes and upgrade to the latest version

**Comment by SkandanC** [comment]
Hello @joamatab,

I have managed to fix all but 1 error and have opened a PR with my fixes. 

![image](https://user-images.githubusercontent.com/100642027/170856294-aaac7628-273c-41e6-ab95-bfa6479b2cd1.png)

**Comment by joamatab** [comment]
Hi Skandan,

i fixed that test but there are still other failing

![image](https://user-images.githubusercontent.com/4514346/171295501-9137653a-3fde-4659-bac8-b2239df4bcfb.png)

can you fix this branch? 
https://github.com/gdsfactory/gdsfactory/tree/simphony_latest3

**Comment by SkandanC** [comment]
Hello Joaquin, 

The errors arise from SiPANN where a specific set of lines cause this issue. 
![image](https://user-images.githubusercontent.com/100642027/171299980-62e62e92-9d63-4b8a-bc65-f95e259691a0.png)
As you can see in the image above, line 465 is the culprit. With this, I am able to reproduce your errors.

![image](https://user-images.githubusercontent.com/100642027/171300393-6edc6ae7-edf6-4034-983e-3bdb6da0db70.png)

Changing the line to `if not all(...` fixes the issue.

I will let Austen and Seqouia know about this, and we will fix this as early as we can.

Let me know if you have any more comments.

**Comment by SkandanC** [comment]
The issue has been fixed.

**Comment by joamatab** [comment]
Can you make a new release for simphony with the new fixes?

**Comment by joamatab** [comment]
Awesome, can you send a new PR after @seqouiap and @autsp release a new sipann?

**Comment by SkandanC** [comment]
> Awesome, can you send a new PR after @seqouiap and @autsp release a new sipann? 

Sure!

**Comment by joamatab** [comment]
That PR was closed a while ago 

A new PR based on current master would be great

**Comment by SkandanC** [comment]
Hello @joamatab,

I was looking at the ring_single errors, and I modified the component to use Simphony's built in single bus ring resonator (built using sipann) component instead of approximating it with a straight waveguide and a half ring. 

I got much closer to the ideal values this time:

![image](https://user-images.githubusercontent.com/100642027/174197555-f33ac0b4-9a3f-4453-b27f-f805b5fa744c.png)

What do you think about this?

**Comment by joamatab** [comment]
Looks good, also the add grating couplers function did not work after the last merge request

**Comment by SkandanC** [comment]
Could you post a screenshot or a snippet of the error?

**Comment by joamatab** [comment]
Sure, you can also just run the add_gc.py file
