### ISSUE TITLE
fix mypy issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#56]
Having clearly defined type annotations helps catch many errors on the code

it would be great having `make mypy` give no type errors.
currently we have > 900 errors

Another type checkers would be pytype, pyre ...

**Comment by elamdf** [comment]
Working on this over [here](https://github.com/elamdf/gdsfactory/tree/fix_mypy), I think it will be a nontrivial undertaking so I may try to take it in segments.

**Comment by sebastian-goeldi** [comment]
I have a few tips (feel free to ignore if you feel comfortable with mypy etc already)

- I strongly suggest to use a plugin that can run in your editor, otherwise you will have to navigate thousands of errors and warnings. I had good experiences with `pyls-mypy`. I believe Joaquin copied settings it over when switching to `pyproject.toml`, so it should be configured correctly automatically.
- strict mode can be annoying, because some times it can feel very much feel like "99 bugs in my code... Fix one, fix another... 154 bugs in my code...". Don't ne discouraged by this ;)
- feel free to tag me if you find a weird one and would like some help. I think I have seen most of the mypy errors you will encounter
