### ISSUE TITLE
Multilayer electrical routing not working

### ISSUE THREAD

**Issue by mdecea** [gdsfactory/gdsfactory#706]
I was trying to use the multilayer electrical routing, but as soon as I try to do routing using, for example `get_route_electrical_multilayer` (from `get_route.py`) I get the following error:

`Traceback (most recent call last):
 [...]

  File "C:\Users\dettz\Dropbox (MIT)\gdsfactory\gdsfactory\components\coh_rx_single_pol.py", line 148, in coh_rx_single_pol
    route = gf.routing.get_route_electrical_multilayer(pd_i1.ports["bot_e3"], pd_i2.ports["top_e3"])

  File "C:\Users\dettz\Dropbox (MIT)\gdsfactory\gdsfactory\routing\get_route.py", line 132, in get_route
    return route_manhattan(

  File "C:\Users\dettz\Dropbox (MIT)\gdsfactory\gdsfactory\routing\manhattan.py", line 1054, in route_manhattan
    points = generate_manhattan_waypoints(

  File "C:\Users\dettz\Dropbox (MIT)\gdsfactory\gdsfactory\routing\manhattan.py", line 977, in generate_manhattan_waypoints
    x = [gf.get_cross_section(xsection[0], **kwargs) for xsection in cross_section]

  File "C:\Users\dettz\Dropbox (MIT)\gdsfactory\gdsfactory\routing\manhattan.py", line 977, in <listcomp>
    x = [gf.get_cross_section(xsection[0], **kwargs) for xsection in cross_section]

TypeError: 'CrossSection' object is not subscriptable
`

I don't understand enough what functionality is this trying to implement. Is it so that one metal layer is used for vertical lines and one for horizontal lines?

**Comment by thomasdorch** [comment]
Hi @mdecea,

First off, there was a bug in the code that I just fixed (PR #707), so thanks for the bug report!

Second, the multilayer routing is implemented in a bit of a hacky way currently, so instead of passing a `CrossSection` into `get_route`, you pass a `MultiCrossSectionAngle`, which is a list of `CrossSection`, angle pairs, _and_ use a `via_corner`, which transitions between layers at 90-degree turns.
from `get_route.py`:
```
get_route_electrical_multilayer = partial(
    get_route_electrical,
    bend=via_corner,
    cross_section=[(metal2, (0, 180)), (metal3, (90, 270))],
)
```
This allows for very simple multilayer routing where you can have vertical routes on one layer and horizontal routes on another.

Hope this helps, let me know if you run into any more issues :)
