### ISSUE TITLE
meep plugin requires fixing for MPI

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#848]
`pytest gdsfactory/simulation/gmeep/test_write_sparameters_meep.py` is not working with gdstk backend

the failing code is coming from
`write_sparameters_meep_mpi.py`

We can't pickle gdstk Cells so maybe it's cleaning writing and reading them using GDS instead of pickle

**Comment by simbilod** [comment]
I'm on it

**Comment by simbilod** [comment]
See #849

**Comment by joamatab** [comment]
Thank you Simon for your PR, notice that the MPI tests are still failing

**Comment by simbilod** [comment]
on my end it was failing due to h5py, so I thought it was something wrong with my setup

`ImportError: /usr/local/google/home/bilodeaus/miniconda3/envs/gdsfactory4_meep/lib/python3.10/site-packages/h5py/defs.cpython-310-x86_64-linux-gnu.so: undefined symbol: H5Pget_fapl_direct`

I can look into it more later

**Comment by joamatab** [comment]
I get only wavelengths in the output

**Comment by joamatab** [comment]
fixed, the ports were missing

`write_gds_with_metadata` instead of `write_gds` fixed the issue
